apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notary
    corda.network: utn
  name: notary
spec:
  type: LoadBalancer
  ports:
  - name: "p2p"
    port: 10002
    targetPort: 10002
  selector:
    app: notary
