apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: supplier0
  name: supplier0
spec:
  type: LoadBalancer
  ports:
  - name: "p2p"
    port: 10002
    targetPort: 10002
  - name: "receiver"
    port: 10004
    targetPort: 10004
  selector:
    app: supplier0
