kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
#  skuName: Standard_LRS
#  location: westeurope
# REMEMBER TO CONFIGURE THE STORAGE ACCOUNT NAME TO THE ONE YOU HAVE CREATED IN AZURE
  storageAccount: cordastorage2
