
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder7
  labels:
    owner: funder7
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
