
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder11
  labels:
    owner: funder11
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
