---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-notary
  labels:
    owner: notary
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
