---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-notary
  labels:
    owner: notary
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-conductor
  labels:
    owner: conductor
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-buyer
  labels:
    owner: buyer
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-supplier1
  labels:
    owner: supplier1
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder
  labels:
    owner: funder
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder0
  labels:
    owner: funder0
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder1
  labels:
    owner: funder1
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder2
  labels:
    owner: funder2
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder3
  labels:
    owner: funder3
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder4
  labels:
    owner: funder4
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder5
  labels:
    owner: funder5
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder6
  labels:
    owner: funder6
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder7
  labels:
    owner: funder7
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder8
  labels:
    owner: funder8
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-funder9
  labels:
    owner: funder9
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
