kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-supplier0
  labels:
    owner: supplier0
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
