# Remember to change/configure the node.conf and this file for testnet. Note - Controller, Networkmap service
# If the plugin is not updated in the image, try rebuild
version: '3.3'
services:

  TradeIX:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 1.0.0
    env_file:
      - ./config/dockerconfig/nodes/corda_docker.env
    ports:
      - "10005:10002"
      - "10006:10003"
      - "10007:10004"
    image: concord:1.0
    container_name: tradeix
    volumes:
      - ./config/dockerconfig/nodes/TradeIX/node.conf:/opt/corda/node.conf
      - ./config/dockerconfig/nodes/plugins/:/opt/corda/plugins/
      - ./config/dockerconfig/nodes/TradeIX/certificates/:/opt/corda/certificates/
      - ./config/dockerconfig/nodes/TradeIX/persistence.mv.db:/opt/corda/persistence.mv.db
    depends_on:
      - Controller

  TradeIXFakeSupplier:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 1.0.0
    env_file:
      - ./config/dockerconfig/nodes/corda_docker.env
    ports:
      - "10008:10002"
      - "10009:10003"
      - "10010:10004"
    image: concord:1.0
    container_name: tradeixfakesupplier
    volumes:
      - ./config/dockerconfig/nodes/TradeIXFakeSupplier/node.conf:/opt/corda/node.conf
      - ./config/dockerconfig/nodes/plugins/:/opt/corda/plugins/
      - ./config/dockerconfig/nodes/TradeIXFakeSupplier/certificates/:/opt/corda/certificates/
      - ./config/dockerconfig/nodes/TradeIXFakeSupplier/persistence.mv.db:/opt/corda/persistence.mv.db
    depends_on:
      - Controller

  TradeIXTestBuyer:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 1.0.0
    env_file:
      - ./config/dockerconfig/nodes/corda_docker.env
    ports:
      - "10023:10002"
      - "10024:10003"
      - "10025:10004"
    image: concord:1.0
    container_name: tradeixtestbuyer
    volumes:
      - ./config/dockerconfig/nodes/TradeIXTestBuyer/node.conf:/opt/corda/node.conf
      - ./config/dockerconfig/nodes/plugins/:/opt/corda/plugins/
      - ./config/dockerconfig/nodes/TradeIXTestBuyer/certificates/:/opt/corda/certificates/
      - ./config/dockerconfig/nodes/TradeIXTestBuyer/persistence.mv.db:/opt/corda/persistence.mv.db
    depends_on:
      - Controller

  TradeIXTestFunder:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 1.0.0
    env_file:
      - ./config/dockerconfig/nodes/corda_docker.env
    ports:
      - "10020:10002"
      - "10021:10003"
      - "10022:10004"
    image: concord:1.0
    container_name: tradeixtestbuyer
    volumes:
      - ./config/dockerconfig/nodes/TradeIXTestFunder/node.conf:/opt/corda/node.conf
      - ./config/dockerconfig/nodes/plugins/:/opt/corda/plugins/
      - ./config/dockerconfig/nodes/TradeIXTestFunder/certificates/:/opt/corda/certificates/
      - ./config/dockerconfig/nodes/TradeIXTestFunder/persistence.mv.db:/opt/corda/persistence.mv.db
    depends_on:
      - Controller

  TradeIXTestSupplier:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 1.0.0
    env_file:
      - ./config/dockerconfig/nodes/corda_docker.env
    ports:
      - "10011:10002"
      - "10012:10003"
      - "10013:10004"
    image: concord:1.0
    container_name: tradeixtestsupplier
    volumes:
      - ./config/dockerconfig/nodes/TradeIXTestSupplier/node.conf:/opt/corda/node.conf
      - ./config/dockerconfig/nodes/plugins/:/opt/corda/plugins/
      - ./config/dockerconfig/nodes/TradeIXTestSupplier/certificates/:/opt/corda/certificates/
      - ./config/dockerconfig/nodes/TradeIXTestSupplier/persistence.mv.db:/opt/corda/persistence.mv.db
    depends_on:
      - Controller

  TradeIXTestSupplier1:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 1.0.0
    env_file:
      - ./config/dockerconfig/nodes/corda_docker.env
    ports:
      - "10014:10002"
      - "10015:10003"
      - "10016:10004"
    image: concord:1.0
    container_name: tradeixtestsupplier1
    volumes:
      - ./config/dockerconfig/nodes/TradeIXTestSupplier1/node.conf:/opt/corda/node.conf
      - ./config/dockerconfig/nodes/plugins/:/opt/corda/plugins/
      - ./config/dockerconfig/nodes/TradeIXTestSupplier1/certificates/:/opt/corda/certificates/
      - ./config/dockerconfig/nodes/TradeIXTestSupplier1/persistence.mv.db:/opt/corda/persistence.mv.db
    depends_on:
      - Controller

  TradeIXTestSupplier2:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 1.0.0
    env_file:
      - ./config/dockerconfig/nodes/corda_docker.env
    ports:
      - "10017:10002"
      - "10018:10003"
      - "10019:10004"
    image: concord:1.0
    container_name: tradeixtestsupplier2
    volumes:
      - ./config/dockerconfig/nodes/TradeIXTestSupplier2/node.conf:/opt/corda/node.conf
      - ./config/dockerconfig/nodes/plugins/:/opt/corda/plugins/
      - ./config/dockerconfig/nodes/TradeIXTestSupplier2/certificates/:/opt/corda/certificates/
      - ./config/dockerconfig/nodes/TradeIXTestSupplier2/persistence.mv.db:/opt/corda/persistence.mv.db
    depends_on:
      - Controller
networks:
  corda: