
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-conductor
  labels:
    owner: conductor
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
