
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-__ID__
  labels:
    owner: __ID__
spec:
  accessModes:
    - ReadWriteOnce
#  volumeName: pv01
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
