apiVersion: "apps/v1beta1"
kind: Deployment
metadata:
  name: buyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buyer
  template:
    metadata:
      labels:
        app: buyer
    spec:
      containers:
# Remember to edit the image as required
      - name: node
        image: tradeixdev.azurecr.io/corda:1.0.0.0
        args: ["controller"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/buyer.conf"
        ports:
        - containerPort: 10002
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: pvclaim
          mountPath: /opt/corda/certificates
          subPath: certificates
        - name: pvclaim
          mountPath: /opt/corda/logs
          subPath: logs
        - name: pvclaim
          mountPath: db
      - name: web
        image: tradeixdev.azurecr.io/corda:1.0.0.0
        args: ["web","buyer"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/buyer.conf"
        ports:
        - containerPort: 10004
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: pvclaim
          mountPath: /opt/corda/certificates
          subPath: certificates
        - name: pvclaim
          mountPath: /opt/corda/logs
          subPath: logs
      imagePullSecrets:
      - name: acr-secret
      volumes:
      - name: certificates
        emptyDir: {}
      - name: config
        configMap:
          name: corda
#      - name: logs
#        emptyDir: {}
      - name: pvclaim
        persistentVolumeClaim:
          claimName: pvclaim-buyer
          readOnly: false
