apiVersion: "apps/v1beta1"
kind: Deployment
metadata:
  name: buyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buyer
  template:
    metadata:
      labels:
        app: buyer
    spec:
      containers:
      - name: node
        image: corda:1.0.0
        args: ["controller"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/buyer.conf"
        ports:
        - containerPort: 10002
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: certificates
          mountPath: /opt/corda/certificates
      - name: web
        image: corda:1.0.0
        args: ["web","buyer"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/buyer.conf"
        ports:
        - containerPort: 10004
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: certificates
          mountPath: /opt/corda/certificates
      volumes:
      - name: certificates
        emptyDir: {}
      - name: config
        configMap:
          name: corda
