apiVersion: "apps/v1beta1"
kind: Deployment
metadata:
  name: conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conductor
  template:
    metadata:
      labels:
        app: conductor
    spec:
      containers:
# Remember to edit the image as required
      - name: node
        image: tradeixdev.azurecr.io/corda:1.0.0.0
        args: ["controller"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/conductor.conf"
        ports:
        - containerPort: 10002
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: pvclaim
          mountPath: /opt/corda/certificates
          subPath: certificates
        - name: pvclaim
          mountPath: /opt/corda/logs
          subPath: logs
        - name: pvclaim
          mountPath: db
#        - name: pvclaim
#          mountPath: /tixintegration
#          readOnly: true
      - name: web
        image: tradeixdev.azurecr.io/corda:1.0.0.0
        args: ["web", "conductor"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/conductor.conf"
        ports:
        - containerPort: 10004
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: pvclaim
          mountPath: /opt/corda/certificates
          subPath: certificates
        - name: pvclaim
          mountPath: /opt/corda/logs
          subPath: logs
#        - name: pvclaim
#          mountPath: /tixintegration
#          readOnly: true
      imagePullSecrets:
      - name: acr-secret
#      volumes:
#      - name: tixintegration
#        configMap:
#          name: tixintegration
      volumes:
      - name: config
        configMap:
          name: corda
      - name: pvclaim
        persistentVolumeClaim:
          claimName: pvclaim-conductor
          readOnly: false
