apiVersion: "apps/v1beta1"
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
# Remember to edit the image as required
      - name: node
        image: tradeixdev.azurecr.io/corda:1.0.0.0
        args: ["none"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/controller.conf"
        ports:
        - containerPort: 10002
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: pvclaim
          mountPath: /opt/corda/certificates
          subPath: certificates
        - name: pvclaim
          mountPath: /opt/corda/logs
          subPath: logs
        - name: pvclaim
          mountPath: db
      imagePullSecrets:
      - name: acr-secret
      volumes:
      - name: config
        configMap:
          name: corda
      - name: logs
        emptyDir: {}
      - name: pvclaim
        persistentVolumeClaim:
          claimName: pvclaim-controller
          readOnly: false
