apiVersion: "apps/v1beta1"
kind: Deployment
metadata:
  name: notary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notary
  template:
    metadata:
      labels:
        app: notary
    spec:
      containers:
      - name: node
        image: tradeixdev.azurecr.io/notary:1.0
        imagePullPolicy: Always
        args: ["none"]
        ports:
        - containerPort: 10002
        volumeMounts:
        - name: pvclaim
          mountPath: /opt/corda/node.conf
          subPath: node.conf
          readOnly: true
        - name: additional-node-infos
          mountPath: "/opt/corda/additional-node-infos/"
          readOnly: true
        - name: notary-certificates
          mountPath: "/opt/corda/certificates/"
          readOnly: true
        - name: notary-nodeinfo
          mountPath: /opt/corda/nodeInfo
          subPath: nodeInfo
        - name: pvclaim
          mountPath: /opt/corda/logs
          subPath: logs
        - name: pvclaim
          mountPath: /opt/corda/network-parameters
          subPath: network-parameters
        - name: pvclaim
          mountPath: /opt/corda/persistence.mv.db
          subPath: persistence.mv.db
        - name: pvclaim
          mountPath: /opt/corda/whitelist.txt
          subPath: whitelist.txt
      imagePullSecrets:
      - name: acr-secret
      volumes:
      - name: notary-nodeinfo
        secret:
          secretName: notary-nodeinfo
      - name: additional-node-infos
        secret:
          secretName: additional-node-infos
      - name: notary-certificates
        secret:
          secretName: notary-certificates
      - name: logs
        emptyDir: {}
      - name: pvclaim
        persistentVolumeClaim:
          claimName: pvclaim-notary
          readOnly: false
