apiVersion: "apps/v1beta1"
kind: Deployment
metadata:
  name: supplier1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier1
  template:
    metadata:
      labels:
        app: supplier1
    spec:
# Remember to edit the image as required
      containers:
      - name: node
        image: tradeixdev.azurecr.io/corda:1.0.0.0
        args: ["controller"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/supplier1.conf"
        ports:
        - containerPort: 10002
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: pvclaim
          mountPath: /opt/corda/certificates
          subPath: certificates
        - name: pvclaim
          mountPath: /opt/corda/logs
          subPath: logs
        - name: pvclaim
          mountPath: db
      - name: web
        image: tradeixdev.azurecr.io/corda:1.0.0.0
        args: ["web", "supplier1"]
        env:
        - name: "CONFIG_FILE"
          value: "/config/supplier1.conf"
        ports:
        - containerPort: 10004
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: pvclaim
          mountPath: /opt/corda/certificates
          subPath: certificates
        - name: pvclaim
          mountPath: /opt/corda/logs
          subPath: logs
      imagePullSecrets:
      - name: acr-secret
      volumes:
      - name: certificates
        emptyDir: {}
      - name: config
        configMap:
          name: corda
      - name: logs
        emptyDir: {}
      - name: pvclaim
        persistentVolumeClaim:
          claimName: pvclaim-supplier1
          readOnly: false
