apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: conductor
  name: conductor
spec:
  type: LoadBalancer
  ports:
  - name: "p2p"
    port: 10002
    targetPort: 10002
  - name: "web"
    port: 8080
    targetPort: 8080
  selector:
    app: conductor
