---
kind: Service
apiVersion: v1
metadata:
  name: tix-service
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
# Remember to change the IP address and port of the RabbitMQ service
kind: Endpoints
apiVersion: v1
metadata:
  name: tix-service
subsets:
  - addresses:
      - ip: 172.20.0.4
    ports:
      - port: 5672
---
